version: "3.9"

services:
  dodgers-alert:
    build: .
    container_name: dodgers-alert
    restart: unless-stopped
    volumes:
      - ./logs:/var/log  # Optional: persistent logs
    environment:
      TZ: America/Los_Angeles
