services:
  dodgers-express:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dodgers-express
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs  # Persist logs on host
    tty: true
